### ISSUE TITLE
Intuition on GCE

### ISSUE THREAD

**Issue by josejhlee** [kakaoenterprise/Learning-Debiased-Disentangled#5]
Hello dear authors,

I was wondering if I could have some clarifications on GCE.

1. GCE is almost an interpolation between CCE and MAE. Their respective derivates are the following:
![image](https://user-images.githubusercontent.com/70194535/151508824-b44878da-56b6-4a52-949f-c306143931d6.png)
2. While CCE dynamically attributes different "weight" (1/f(x)) according to the difficulty of the sample, MAE is uniform across all samples.
3. Usually, "difficult" samples are bias-conflicting samples. Thus, the gradient is higher CCE for this scenario.
4. On the other hand, GCE attributes less gradient in the same scenario. Thus,  GCE is less attentive to "difficult" samples, which in turn allocates more attention to "easier" samples in expectation. Therefore, GCE is less focused on intrinsic attributes and seeks after shortcuts

The reason I doubt my statement is due to your clarifications on GCE in OpenReview.
![image](https://user-images.githubusercontent.com/70194535/151511275-8c084612-e3bd-4190-994d-166f32033af6.png)
I thought GCE was more attentive to the bias element not because it emphasizes the easy samples but de-emphasizes the hard ones.

Thank you for your attention and great paper!

**Comment by leebebeto** [comment]
Thanks for the question! 
I think it is the same thing because reweighting is a relative operation.
In other words, if you emphasize easy samples (bias-aligned samples), you naturally de-emphasize the hard ones (bias-conflicting samples), so I think the way you understand the intuition is same as our explanation.

Sorry for the late reply
Thank you!
